# Generated by Django 5.1.2 on 2024-10-27 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_loan_description_loan_progress_loan_purpose_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Funding', 'Funding'), ('Funded', 'Funded')], default='Available', max_length=20),
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('merchant_request_id', models.CharField(max_length=100, null=True)),
                ('checkout_request_id', models.CharField(max_length=100, null=True)),
                ('response_code', models.CharField(max_length=5, null=True)),
                ('response_description', models.CharField(max_length=255, null=True)),
                ('customer_message', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
